####################################################### ACCOUNT
#POST ACCOUNT
POST http://localhost:5060/account/create HTTP/1.1
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "asd",
  "email": "morici@gmail.com",
  "birthday": "23/08/1992",
  "password": "lamiapassword"
}

####
#GET ALL ACCOUNT
GET http://localhost:5060/accounts

####
#GET ALL ACCOUNT ADMIN
GET http://localhost:5060/adminAccounts

####
#GET ALL ACCOUNT USER
GET http://localhost:5060/userAccounts

####
#GET ACCOUNT BY ID
GET http://localhost:5060/account/654683ab30e3a3822b50c9aa

####
#PATCH ACCOUNT
PATCH http://localhost:5060/account/update/6546849faed7cb509be01df7 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Deborah",
  "lastName": "Di Gennaro",
  "email": "debby@gmail.com",
  "birthday": "08/08/1994",
  "role": "user"
}

####
#DELETE ACCOUNT
DELETE http://localhost:5060/account/delete/654689e44aef9f82eef8b165





####################################################### GAME
#POST GAME
POST http://localhost:5060/game/create HTTP/1.1
Content-Type: application/json

{
  "title": "Elden Radasdasding",
  "category": "RPG",
  "description": "Diventa un super Sayan! di rabbia",
  "platform": "PlayStation/Xbox/PC",
  "editor": "From Software",
  "rate": 10,
  "price": 60
}

####
#GET ALL GAMES
GET http://localhost:5060/games

####
#GET GAME BY ID
GET http://localhost:5060/game/6548f87f8c21e22333981daf

####
#GET GAME BY CATEGORY
GET http://localhost:5060/games/category/Adventure

####
#GET GAME BY EDITOR
GET http://localhost:5060/games/editor/Marvel

####
#GET GAME BY TITLE
GET http://localhost:5060/games/byTitle?title=zelda

####
#GET GAME BY DATE
GET http://localhost:5060/games/byDate/2023-11-06

####
#PATCH GAME
PATCH http://localhost:5060/game/update/6548f8f87d1b96b07b9dfcf7 HTTP/1.1
Content-Type: application/json

{
  "editor": "Bandai Namco"
}

####
#DELETE GAME
DELETE http://localhost:5060/game/delete/654a5c95d26df180a36a3839



####################################################### POST
#POST POST
POST http://localhost:5060/post/create HTTP/1.1
Content-Type: application/json

{
  "author": "654683ab30e3a3822b50c9aa",
  "game": "Final Fantasy",
  "title": "C'è qualche Gilda ITA?",
  "content": "proviamo e vediamo se funziona",
  "img": "https://cvj.ch/wp-content/uploads/2022/01/CVJ.CH-Play-to-Earn-P2E-Gaming.jpg",
  "category": "Party"
}

####
#GET ALL POST
GET http://localhost:5060/posts

####
#GET POST BY ID
GET http://localhost:5060/post/654a6f839675daa333386f15

####
#GET POST BY TITLE
GET http://localhost:5060/posts/byTitle?title=primo

####
#GET POST BY DATE
GET http://localhost:5060/posts/byDate/2023-11-08

####
#GET POST BY CATEGORY
GET http://localhost:5060/posts/category/Nuove uscite

####
#PATCH GAME
PATCH http://localhost:5060/post/update/654a6fd89675daa333386f17 HTTP/1.1
Content-Type: application/json

{
  "title": "secondo post modificato"
}

####
#DELETE GAME
DELETE http://localhost:5060/post/delete/654ba58b7b3b0353ea2ff600

####################################################### COMMENT
#POST COMMENT
POST http://localhost:5060/comment/create HTTP/1.1
Content-Type: application/json

{
  "author": "654683ab30e3a3822b50c9aa",
  "game": "6548f87f8c21e22333981daf",
  "title": "1456",
  "content": "proviamo e vediamo se funziona"
}

####
#GET ALL COMMENT
GET http://localhost:5060/comments

####
#GET ALL COMMENT BY GAME ID
GET http://localhost:5060/game/viewComments/6548f78b8c21e22333981dad

####
#GET ALL COMMENT BY POST ID
GET http://localhost:5060/post/viewComments/654a6f839675daa333386f15

####
#GET COMMENT BY ID
GET http://localhost:5060/comment/654cf9d40891acd9099bee8d

####
#PATCH COMMENT
PATCH http://localhost:5060/comment/update/654cf9d40891acd9099bee8d HTTP/1.1
Content-Type: application/json

{
  "content": "commento modificato"
}

####
#DELETE COMMENT
DELETE http://localhost:5060/comment/delete/654cf9d40891acd9099bee8d
